# Data Pre-processing

## Setup

Run the cell below to import necessary modules.

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [ ]:
anime_path = '/content/drive/My Drive/anime.csv' # Path to anime dataset in drive
animelist_path = '/content/drive/My Drive/animelist.csv' # Path to anime dataset in drive
anime_with_synopsis_path = '/content/drive/My Drive/anime_with_synopsis.csv' # Path to anime dataset in drive

In [ ]:
anime_df = pd.read_csv(anime_path)
animelist_df = pd.read_csv(animelist_path)
anime_with_synopsis_df = pd.read_csv(anime_with_synopsis_path)

In [ ]:
anime_df.head(1)

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0

In [ ]:
animelist_df.head(1)

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1

In [ ]:
anime_with_synopsis_df.head(1)

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."

## Clean Missing Values

## anime dataframe

In [ ]:
clean_anime = anime_df.replace({'Unknown':np.nan})
clean_anime.dropna(inplace=True)
clean_anime.reset_index(inplace=True, drop=True)

In [ ]:
clean_anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
2,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
3,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",Honey and Clover,ハチミツとクローバー,TV,24,"Apr 15, 2005 to Sep 27, 2005",Spring 2005,...,11829.0,16309.0,20008.0,13062.0,5574.0,3148.0,1339.0,484.0,278.0,321.0
4,19,Monster,8.76,"Drama, Horror, Mystery, Police, Psychological,...",Monster,モンスター,TV,74,"Apr 7, 2004 to Sep 28, 2005",Spring 2004,...,77350.0,60652.0,43459.0,22045.0,8861.0,4381.0,2086.0,882.0,593.0,1177.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,41694,Hataraku Saibou Black (TV),7.57,"Action, Seinen",Cells at Work! CODE BLACK!,はたらく細胞BLACK,TV,13,"Jan 10, 2021 to ?",Winter 2021,...,1188.0,1892.0,4929.0,4700.0,1441.0,503.0,143.0,65.0,25.0,30.0
1580,41911,Hanyou no Yashahime: Sengoku Otogizoushi,6.86,"Action, Adventure, Comedy, Historical, Demons,...",Yashahime:Princess Half-Demon,半妖の夜叉姫,TV,24,"Oct 3, 2020 to ?",Fall 2020,...,1149.0,1010.0,2219.0,3473.0,2219.0,1340.0,556.0,202.0,100.0,350.0
1581,41930,Kamisama ni Natta Hi,6.86,"Drama, Fantasy",The Day I Became a God,神様になった日,TV,12,"Oct 11, 2020 to Dec 27, 2020",Fall 2020,...,4886.0,5738.0,12528.0,17585.0,11032.0,5688.0,3257.0,1477.0,762.0,661.0
1582,42897,Horimiya,8.6,"Slice of Life, Comedy, Romance, School, Shounen",Horimiya,ホリミヤ,TV,13,"Jan 10, 2021 to ?",Winter 2021,...,24190.0,28488.0,24494.0,9619.0,2458.0,1023.0,310.0,135.0,75.0,337.0
1583,42923,SK∞,7.96,"Comedy, Sports",SK8 the Infinity,SK∞ エスケーエイト,TV,12,"Jan 10, 2021 to ?",Winter 2021,...,5577.0,6361.0,10385.0,6966.0,2101.0,803.0,250.0,85.0,40.0,83.0

## animelist dataframe

In [ ]:
clean_animelist = animelist_df.rename(columns={'anime_id':'MAL_ID'})

In [ ]:
clean_animelist

           user_id  MAL_ID  rating  watching_status  watched_episodes
0                0      67       9                1                 1
1                0    6702       7                1                 4
2                0     242      10                1                 4
3                0    4898       0                1                 1
4                0      21      10                1                 0
...            ...     ...     ...              ...               ...
109224742   353404     507       7                2                 2
109224743   353404     392       9                2               112
109224744   353404     882       6                2                 1
109224745   353404     883       8                2                 1
109224746   353404     149       0                6                 0

[109224747 rows x 5 columns]

## anime_wiht_synopsis dataframe

In [ ]:
clean_anime_with_synopsis = anime_with_synopsis_df.replace({'Unknown':np.nan})
clean_anime_with_synopsis.dropna(inplace=True)
clean_anime.reset_index(inplace=True, drop=True)

In [ ]:
clean_anime_with_synopsis

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...
...,...,...,...,...,...
16157,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,Valentine's Day special for Kimetsu no Yaiba ....
16158,47402,Heikousen,7.52,"Music, Romance","usic video for Eve and suis' song Heikousen , ..."
16165,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",No synopsis information has been added to this...
16166,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",cap of the first season of Yakusoku no Neverla...
16204,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",cap of the first 9 episodes of SK∞ .

## Entity Resolution

Need to split the genre coloumn for clean_anime to be able to filter on genre

In [ ]:
clean_anime['Genres'] = clean_anime.apply(lambda x: [j.strip() for j in x['Genres'].split(",")],axis=1)

In [ ]:
clean_anime = clean_anime.explode('Genres')

In [ ]:
clean_anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,Action,Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
0,1,Cowboy Bebop,8.78,Adventure,Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
0,1,Cowboy Bebop,8.78,Comedy,Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
0,1,Cowboy Bebop,8.78,Drama,Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
0,1,Cowboy Bebop,8.78,Sci-Fi,Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,42897,Horimiya,8.6,Romance,Horimiya,ホリミヤ,TV,13,"Jan 10, 2021 to ?",Winter 2021,...,24190.0,28488.0,24494.0,9619.0,2458.0,1023.0,310.0,135.0,75.0,337.0
1582,42897,Horimiya,8.6,School,Horimiya,ホリミヤ,TV,13,"Jan 10, 2021 to ?",Winter 2021,...,24190.0,28488.0,24494.0,9619.0,2458.0,1023.0,310.0,135.0,75.0,337.0
1582,42897,Horimiya,8.6,Shounen,Horimiya,ホリミヤ,TV,13,"Jan 10, 2021 to ?",Winter 2021,...,24190.0,28488.0,24494.0,9619.0,2458.0,1023.0,310.0,135.0,75.0,337.0
1583,42923,SK∞,7.96,Comedy,SK8 the Infinity,SK∞ エスケーエイト,TV,12,"Jan 10, 2021 to ?",Winter 2021,...,5577.0,6361.0,10385.0,6966.0,2101.0,803.0,250.0,85.0,40.0,83.0
1583,42923,SK∞,7.96,Sports,SK8 the Infinity,SK∞ エスケーエイト,TV,12,"Jan 10, 2021 to ?",Winter 2021,...,5577.0,6361.0,10385.0,6966.0,2101.0,803.0,250.0,85.0,40.0,83.0

## Export Data

In [ ]:
clean_anime.to_csv("anime_clean.csv", index=False)
clean_animelist.to_csv("animelist_clean.csv", index=False)
clean_anime_with_synopsis.to_csv("anime_with_synopsis_clean.csv", index=False)

In [ ]:
from google.colab import files
files.download('anime_clean.csv') 
files.download("animelist_clean.csv")
files.download("anime_with_synopsis_clean.csv")